### ISSUE TITLE
[roadshow] Logging lab... need to add instructions on how to set the default index

### ISSUE THREAD

**Issue by alberttwong** [openshift-evangelists/openshift-workshops#60]

**Comment by thoraxe** [comment]
This is a known issue with Kibana and is related to how long it was after the project was created before you access it within Kibana. It has nothing to do with the lab itself. Since you are not creating any projects in the lab(s), you should almost never encounter this issue.

* When did you install Kibana?
* When did you create the project?
* When did you try to access Kibana?
